import type { Metadata } from "next";
import { Clock3, Mail, MapPin, Phone, Send } from "lucide-react";
import { ContactForm } from "@/components/contact/ContactForm";
import { StoreShell } from "@/components/layout/StoreShell";
import { PageIntro } from "@/components/shared/PageIntro";

export const metadata: Metadata = { title: "Aloqa — Kitob.go", description: "Kitob.go bilan telefon, Telegram yoki murojaat formasi orqali bog‘laning." };

export default function ContactPage() {
  return <StoreShell><PageIntro eyebrow="Doim aloqadamiz" title="Sizga qanday yordam bera olamiz?" description="Buyurtma, kitob tanlash yoki hamkorlik bo‘yicha savolingiz bo‘lsa, biz bilan bog‘laning." breadcrumbs={[{ label: "Aloqa" }]} /><section className="container-page py-8 sm:py-12"><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr] xl:gap-8"><div className="space-y-4"><ContactCard icon={Phone} label="Telefon" value="+998 71 200 00 00" href="tel:+998712000000" note="Har kuni 09:00–21:00" /><ContactCard icon={Send} label="Telegram" value="@kitobgo" href="https://t.me/kitobgo" note="Odatda 10 daqiqada javob beramiz" /><ContactCard icon={Mail} label="Elektron pochta" value="salom@kitob.go" href="mailto:salom@kitob.go" note="Hamkorlik va takliflar uchun" /><div className="rounded-2xl bg-brand-dark p-6 text-white"><MapPin className="text-brand-gold" /><h2 className="mt-5 font-extrabold">Ofisimiz</h2><p className="mt-2 text-sm leading-6 text-white/70">Toshkent shahri, Shayxontohur tumani, Navoiy ko‘chasi, 18-uy</p><p className="mt-4 flex items-center gap-2 text-xs text-white/65"><Clock3 size={15} /> Dushanba–Shanba, 09:00–19:00</p></div></div><ContactForm /></div></section><section className="border-y border-line bg-white py-10"><div className="container-page"><div className="relative grid min-h-64 place-items-center overflow-hidden rounded-2xl bg-[#E5ECE7] text-center"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(#12633d_1px,transparent_1px),linear-gradient(90deg,#12633d_1px,transparent_1px)] [background-size:32px_32px]" /><div className="relative rounded-2xl bg-white/95 p-6 shadow-card"><span className="mx-auto grid size-11 place-items-center rounded-full bg-brand text-white"><MapPin size={20} /></span><strong className="mt-3 block">Kitob.go markaziy ofisi</strong><small className="text-muted">Toshkent shahri</small></div></div></div></section></StoreShell>;
}

function ContactCard({ icon: Icon, label, value, href, note }: { icon: typeof Phone; label: string; value: string; href: string; note: string }) { return <a href={href} className="group flex items-center gap-4 rounded-2xl border border-line bg-white p-5 transition hover:border-brand/25 hover:shadow-card"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-brand/10 text-brand transition group-hover:bg-brand group-hover:text-white"><Icon size={22} /></span><span><small className="text-muted">{label}</small><strong className="block">{value}</strong><small className="text-muted">{note}</small></span></a>; }
