import type { Metadata } from "next";
import { ArrowRight, BookOpenText, Clock3 } from "lucide-react";
import Link from "next/link";
import { StoreShell } from "@/components/layout/StoreShell";
import { PageIntro } from "@/components/shared/PageIntro";
import { posts } from "@/data/blog";

export const metadata: Metadata = { title: "Blog — Kitob.go", description: "Mutolaa, kitob tanlash va oilaviy kutubxona haqida foydali maqolalar." };

export default function BlogPage() {
  const [featured, ...rest] = posts;
  return <StoreShell><PageIntro eyebrow="Foydali mutolaa" title="Kitob.go blogi" description="Kitob tanlash, mutolaa odati va yangi nashrlar haqida tahririyatimizdan foydali maqolalar." breadcrumbs={[{ label: "Blog" }]} /><section className="container-page py-8 sm:py-12"><Link href={`/blog/${featured.slug}`} className="group grid overflow-hidden rounded-[24px] border border-line bg-white shadow-soft lg:grid-cols-2"><div className="relative grid min-h-64 place-items-center overflow-hidden p-10" style={{ backgroundColor: featured.color }}><div className="absolute -right-16 -top-20 size-64 rounded-full border-[42px] border-white/40" /><BookOpenText size={86} strokeWidth={1} className="relative text-brand/70 transition duration-500 group-hover:scale-110" /></div><div className="flex flex-col justify-center p-6 sm:p-9 lg:p-12"><span className="eyebrow w-fit">Muharrir tanlovi · {featured.category}</span><h2 className="mt-4 text-2xl font-extrabold leading-tight tracking-tight sm:text-3xl">{featured.title}</h2><p className="mt-3 leading-7 text-muted">{featured.excerpt}</p><div className="mt-6 flex items-center gap-4 text-xs text-muted"><span>{featured.date}</span><span className="flex items-center gap-1"><Clock3 size={14} /> {featured.readTime}</span></div><span className="mt-7 inline-flex items-center gap-2 font-bold text-brand">Maqolani o‘qish <ArrowRight size={18} className="transition group-hover:translate-x-1" /></span></div></Link><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{rest.map((post) => <Link key={post.slug} href={`/blog/${post.slug}`} className="group overflow-hidden rounded-2xl border border-line bg-white transition hover:-translate-y-1 hover:border-brand/20 hover:shadow-card"><div className="relative grid aspect-[16/8] place-items-center overflow-hidden" style={{ backgroundColor: post.color }}><BookOpenText size={48} strokeWidth={1.2} className="text-brand/65 transition group-hover:scale-110" /><span className="absolute left-4 top-4 rounded-full bg-white/90 px-3 py-1 text-[11px] font-bold text-brand">{post.category}</span></div><div className="p-5"><h2 className="text-lg font-extrabold leading-6">{post.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{post.excerpt}</p><div className="mt-5 flex items-center justify-between text-xs text-muted"><span>{post.date}</span><span>{post.readTime}</span></div></div></Link>)}</div></section></StoreShell>;
}
