import type { Metadata } from "next";
import { BadgeCheck, BookHeart, CreditCard, HeartHandshake, RotateCcw, Target, Truck, UsersRound } from "lucide-react";
import Link from "next/link";
import { StoreShell } from "@/components/layout/StoreShell";
import { PageIntro } from "@/components/shared/PageIntro";
import { StatisticsBanner } from "@/components/home/StatisticsBanner";

export const metadata: Metadata = { title: "Biz haqimizda — Kitob.go", description: "Kitob.go jamoasi, maqsadi va xizmat tamoyillari haqida." };

export default function AboutPage() {
  return <StoreShell><PageIntro eyebrow="Kitob.go hikoyasi" title="Ilmni har bir xonadonga yaqinlashtiramiz" description="Biz original, mazmunli va sifatli kitoblarni tanlashdan tortib eshigingizgacha yetkazishgacha bo‘lgan yo‘lni sodda qilamiz." breadcrumbs={[{ label: "Biz haqimizda" }]} /><section className="container-page py-10 sm:py-16"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-[24px] bg-brand-dark p-7 text-white sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-white/10 text-brand-gold"><BookHeart size={24} /></span><h2 className="mt-7 text-3xl font-extrabold tracking-tight">Kitob tanlash xotirjam va zavqli bo‘lishi kerak</h2><p className="mt-4 leading-8 text-white/70">Kitob.go 2022-yilda kitobxonlar uchun ishonchli onlayn manzil yaratish niyatida boshlangan. Bugun biz yuzlab nashrlarni saralab, O‘zbekiston bo‘ylab minglab oilalarga yetkazamiz.</p></div><div className="grid gap-4 sm:grid-cols-2"><Value icon={Target} title="Maqsadimiz" text="Sifatli kitob va kitobxon orasidagi masofani qisqartirish." /><Value icon={BadgeCheck} title="Original nashrlar" text="Faqat rasmiy nashriyot va tekshirilgan hamkorlar." /><Value icon={HeartHandshake} title="Halol xizmat" text="Narx, sifat va yetkazishda ochiq va mas’uliyatli yondashuv." /><Value icon={UsersRound} title="Kitobxon markazda" text="Har bir tavsiya va xizmatda sizning ehtiyojingiz birinchi o‘rinda." /></div></div></section><StatisticsBanner /><section className="border-y border-line bg-white py-12 sm:py-16"><div className="container-page"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">Xizmat tartibi</span><h2 className="mt-3 text-3xl font-extrabold">Xotirjam xarid kafolati</h2></div><div className="mt-9 grid gap-4 md:grid-cols-3"><Info id="delivery" icon={Truck} title="Bepul yetkazib berish" text="Buyurtmalar O‘zbekistonning barcha hududlariga 1–3 ish kuni ichida bepul yetkaziladi. Operator qulay vaqtni siz bilan kelishadi." /><Info id="payment" icon={CreditCard} title="Qabul qilganda to‘lov" text="Oldindan to‘lov shart emas. Kitobni qabul qilib, holatini tekshirganingizdan keyin to‘lovni amalga oshirasiz." /><Info id="returns" icon={RotateCcw} title="14 kun ichida qaytarish" text="Foydalanilmagan va asl holati saqlangan mahsulotni 14 kun ichida qaytarish yoki almashtirish mumkin." /></div></div></section><section className="container-page py-12 sm:py-16"><div className="flex flex-col items-center justify-between gap-5 rounded-[24px] bg-[#E7F0EA] p-7 text-center sm:p-10 lg:flex-row lg:text-left"><div><h2 className="text-2xl font-extrabold sm:text-3xl">Keyingi kitobingizni birga topamiz</h2><p className="mt-2 text-muted">Katalogni ko‘ring yoki maslahatchimizga yozing.</p></div><div className="flex gap-3"><Link href="/catalog" className="button-primary h-12 px-6">Katalogga o‘tish</Link><Link href="/contact" className="button-secondary inline-flex h-12 px-6">Bog‘lanish</Link></div></div></section></StoreShell>;
}

function Value({ icon: Icon, title, text }: { icon: typeof Target; title: string; text: string }) { return <div className="rounded-2xl border border-line bg-white p-5"><span className="grid size-11 place-items-center rounded-xl bg-brand/10 text-brand"><Icon size={21} /></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{text}</p></div>; }
function Info({ id, icon: Icon, title, text }: { id: string; icon: typeof Target; title: string; text: string }) { return <article id={id} className="scroll-mt-44 rounded-2xl border border-line p-6"><span className="grid size-12 place-items-center rounded-xl bg-brand/10 text-brand"><Icon size={23} /></span><h3 className="mt-5 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-7 text-muted">{text}</p></article>; }
