import type { Metadata } from "next";
import { ArrowRight, BookOpen, Search } from "lucide-react";
import Link from "next/link";
import { StoreShell } from "@/components/layout/StoreShell";
import { PageIntro } from "@/components/shared/PageIntro";
import { authors } from "@/data/authors";

export const metadata: Metadata = { title: "Mualliflar — Kitob.go", description: "Sevimli yozuvchi va olimlaringiz asarlarini toping.", alternates: { canonical: "/authors" } };

export default async function AuthorsPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const params = await searchParams;
  const q = params.q?.toLocaleLowerCase("uz") ?? "";
  const filtered = authors.filter((author) => !q || `${author.name} ${author.specialty}`.toLocaleLowerCase("uz").includes(q));
  return <StoreShell><PageIntro eyebrow="Ilm ahli" title="Mualliflar" description="Asarlari qalb va tafakkurni boyitadigan taniqli olim, adib va mutafakkirlar." breadcrumbs={[{ label: "Mualliflar" }]} /><section className="container-page py-8 sm:py-12"><form action="/authors" className="relative mx-auto mb-8 max-w-xl"><label htmlFor="author-search" className="sr-only">Muallif qidirish</label><input id="author-search" name="q" defaultValue={params.q} placeholder="Muallif ismini kiriting" className="h-[52px] w-full rounded-2xl border border-line bg-cream py-3.5 pl-5 pr-14 outline-none focus:border-cocoa focus:ring-4 focus:ring-cocoa/10" /><button className="absolute right-2 top-1/2 grid size-10 -translate-y-1/2 place-items-center rounded-xl bg-cocoa text-cream" aria-label="Qidirish"><Search size={18} /></button></form>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((author) => <article key={author.id} className="group rounded-2xl border border-line bg-cream p-5 transition hover:-translate-y-1 hover:border-cocoa/20 hover:shadow-card sm:p-6"><div className="flex items-start gap-4"><span className="grid size-16 shrink-0 place-items-center rounded-2xl text-lg font-extrabold text-cocoa" style={{ backgroundColor: author.color }}>{author.initials}</span><div><h2 className="font-serif font-semibold leading-6">{author.name}</h2><p className="mt-1 text-xs font-semibold text-cocoa">{author.specialty}</p></div></div><p className="mt-5 text-sm leading-6 text-bodyText">{author.bio}</p><div className="mt-5 flex items-center justify-between border-t border-line pt-4"><span className="inline-flex items-center gap-2 text-xs text-bodyText"><BookOpen size={16} className="text-cocoa" /> {author.booksCount} ta kitob</span><Link href={`/catalog?q=${encodeURIComponent(author.name)}`} className="inline-flex items-center gap-1 text-sm font-bold text-cocoa">Asarlari <ArrowRight size={16} /></Link></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-line bg-cream p-12 text-center"><h2 className="font-serif text-xl font-semibold">Muallif topilmadi</h2><Link href="/authors" className="mt-3 inline-block font-bold text-cocoa">Barchasini ko‘rish</Link></div>}</section></StoreShell>;
}
