import type { Metadata } from "next";
import { ArrowRight, LockKeyhole, Phone, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { StoreShell } from "@/components/layout/StoreShell";

export const metadata: Metadata = { title: "Kirish — Kitob.go" };

export default function LoginPage() {
  return <StoreShell><section className="container-page py-10 sm:py-16"><div className="mx-auto grid max-w-5xl overflow-hidden rounded-[28px] border border-line bg-white shadow-soft lg:grid-cols-[.9fr_1.1fr]"><div className="relative overflow-hidden bg-brand-dark p-7 text-white sm:p-10 lg:p-12"><div className="absolute -bottom-24 -right-24 size-72 rounded-full border-[48px] border-white/5" /><span className="grid size-12 place-items-center rounded-2xl bg-white/10 text-brand-gold"><ShieldCheck size={24} /></span><h1 className="mt-8 text-3xl font-extrabold tracking-tight sm:text-4xl">Shaxsiy kabinetingizga xush kelibsiz</h1><p className="mt-4 max-w-md leading-7 text-white/70">Buyurtmalarni kuzating, sevimli kitoblaringizni saqlang va keyingi xaridni yanada tez amalga oshiring.</p><ul className="mt-8 space-y-4 text-sm text-white/85"><li className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-white/10">✓</span> Buyurtmalar tarixi</li><li className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-white/10">✓</span> Saqlangan manzillar</li><li className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-white/10">✓</span> Maxsus takliflar</li></ul></div><div className="p-7 sm:p-10 lg:p-12"><span className="eyebrow">Akkaunt</span><h2 className="mt-3 text-2xl font-extrabold sm:text-3xl">Telefon raqam orqali kirish</h2><p className="mt-2 text-sm leading-6 text-muted">Tasdiqlash kodi telefon raqamingizga SMS orqali yuboriladi.</p><form action="/profile" className="mt-7"><label htmlFor="phone" className="text-sm font-bold">Telefon raqam</label><div className="relative mt-2"><Phone size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-muted" /><input id="phone" name="phone" type="tel" required defaultValue="+998 " className="h-[52px] w-full rounded-xl border border-line py-3.5 pl-11 pr-4 outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></div><button className="button-primary mt-4 h-12 w-full px-5">Davom etish <ArrowRight size={18} /></button></form><div className="mt-6 flex items-start gap-2 rounded-xl bg-canvas p-4 text-xs leading-5 text-muted"><LockKeyhole size={16} className="mt-0.5 shrink-0 text-brand" /> Davom etish orqali maxfiylik siyosati va foydalanish shartlariga rozilik bildirasiz.</div><p className="mt-7 text-center text-sm text-muted">Yordam kerakmi? <Link href="/contact" className="font-bold text-brand">Biz bilan bog‘laning</Link></p></div></div></section></StoreShell>;
}
