"use client";

import { CheckCircle2, Send } from "lucide-react";
import { useState } from "react";

export function ContactForm() {
  const [sent, setSent] = useState(false);
  if (sent) return <div className="grid min-h-[390px] place-items-center rounded-2xl border border-line bg-white p-8 text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-brand text-white"><CheckCircle2 size={30} /></span><h2 className="mt-5 text-2xl font-extrabold">Xabaringiz yuborildi</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted">Murojaatingizni oldik. Mutaxassisimiz ish vaqti davomida tez orada javob beradi.</p><button type="button" onClick={() => setSent(false)} className="mt-5 text-sm font-bold text-brand">Yana xabar yuborish</button></div></div>;
  return <form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="rounded-2xl border border-line bg-white p-5 shadow-soft sm:p-7"><h2 className="text-xl font-extrabold">Bizga xabar qoldiring</h2><p className="mt-1 text-sm text-muted">Barcha maydonlarni to‘ldiring, siz bilan bog‘lanamiz.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Ismingiz" name="name" placeholder="To‘liq ism" /><Field label="Telefon raqam" name="phone" type="tel" placeholder="+998 90 123 45 67" /><div className="sm:col-span-2"><label htmlFor="topic" className="text-sm font-bold">Murojaat mavzusi</label><select id="topic" name="topic" className="mt-2 h-12 w-full rounded-xl border border-line bg-white px-4 text-sm outline-none focus:border-brand"><option>Buyurtma haqida</option><option>Kitob tanlash bo‘yicha maslahat</option><option>Hamkorlik</option><option>Boshqa savol</option></select></div><div className="sm:col-span-2"><label htmlFor="message" className="text-sm font-bold">Xabar</label><textarea id="message" name="message" required rows={5} placeholder="Savolingizni yozing..." className="mt-2 w-full resize-none rounded-xl border border-line px-4 py-3 text-sm outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></div></div><button type="submit" className="button-primary mt-5 h-12 px-6"><Send size={18} /> Xabarni yuborish</button></form>;
}

function Field({ label, name, placeholder, type = "text" }: { label: string; name: string; placeholder: string; type?: string }) { return <div><label htmlFor={name} className="text-sm font-bold">{label}</label><input id={name} name={name} type={type} required placeholder={placeholder} className="mt-2 h-12 w-full rounded-xl border border-line px-4 text-sm outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" /></div>; }
